-- Create the tools table for Serp-scale-AI directory
-- This table stores AI tool listings with comprehensive metadata

CREATE TABLE tools (
    -- Primary key with auto-incrementing bigint
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Timestamp for record creation tracking
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    
    -- Core tool information
    name text NOT NULL,
    short_description text NOT NULL,
    full_description text,
    
    -- URLs for branding and navigation
    logo_url text,
    website_url text NOT NULL,
    
    -- Rating system (allows values like 4.5, 3.2, etc.)
    rating numeric(2, 1),
    
    -- Classification and categorization
    pricing_model text,
    category text,
    
    -- FAQ data stored as JSON array of question/answer objects
    -- Example: [{"q": "Is this tool free?", "a": "Yes, it has a free tier"}, ...]
    faqs jsonb,
    
    -- Feature flag for editorial curation
    is_featured boolean DEFAULT false NOT NULL
);

-- Enable Row Level Security (RLS) for enhanced data protection
-- This ensures that data access is controlled at the database level
-- Configure RLS policies separately based on your authentication requirements
ALTER TABLE tools ENABLE ROW LEVEL SECURITY;

-- Create indexes for better query performance
CREATE INDEX idx_tools_category ON tools(category);
CREATE INDEX idx_tools_featured ON tools(is_featured);
CREATE INDEX idx_tools_rating ON tools(rating);
CREATE INDEX idx_tools_created_at ON tools(created_at);

-- Add comments for documentation
COMMENT ON TABLE tools IS 'AI tool directory listings for Serp-scale-AI platform';
COMMENT ON COLUMN tools.id IS 'Unique identifier for each tool';
COMMENT ON COLUMN tools.created_at IS 'Timestamp when the tool was added to the directory';
COMMENT ON COLUMN tools.name IS 'Display name of the AI tool';
COMMENT ON COLUMN tools.short_description IS 'Brief summary for tool cards and listings';
COMMENT ON COLUMN tools.full_description IS 'Detailed description for tool detail pages';
COMMENT ON COLUMN tools.logo_url IS 'URL to the tool logo image';
COMMENT ON COLUMN tools.website_url IS 'Official website URL of the tool';
COMMENT ON COLUMN tools.rating IS 'Admin-assigned rating (0.0 to 9.9)';
COMMENT ON COLUMN tools.pricing_model IS 'Pricing structure (e.g., Free, Freemium, Paid, Subscription)';
COMMENT ON COLUMN tools.category IS 'Primary category classification';
COMMENT ON COLUMN tools.faqs IS 'JSON array of FAQ objects with question and answer pairs';
COMMENT ON COLUMN tools.is_featured IS 'Editorial flag to highlight tools as featured/editors picks';
